service: habits-api

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: dotnetcore2.1
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"

package:
  artifact: bin/release/netcoreapp2.1/HabitsEngine.zip

functions:
  get-teams:
    handler: HabitsEngine::Habits.API.TeamHandler::GetAll
    events:
      - http:
          path: api/teams
          method: get
          cors: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-west-2:640097525811:userpool/us-west-2_d6v3kKOTn
  get-team:
    handler: HabitsEngine::Habits.API.TeamHandler::Get
    events:
      - http:
          path: api/teams/{teamId}
          method: get
          request:
            parameters:
              paths:
                teamId: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-west-2:640097525811:userpool/us-west-2_d6v3kKOTn
  post-team:
    handler: HabitsEngine::Habits.API.TeamHandler::Add
    events:
      - http:
          path: api/teams
          method: post
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-west-2:640097525811:userpool/us-west-2_d6v3kKOTn
  put-team:
    handler: HabitsEngine::Habits.API.TeamHandler::Update
    events:
      - http:
          path: api/teams
          method: put
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-west-2:640097525811:userpool/us-west-2_d6v3kKOTn
  delete-team:
    handler: HabitsEngine::Habits.API.TeamHandler::Delete
    events:
      - http:
          path: api/teams/{teamId}
          method: delete
          request:
            parameters:
              paths:
                teamId: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-west-2:640097525811:userpool/us-west-2_d6v3kKOTn
  get-habits:
    handler: HabitsEngine::Habits.API.HabitHandler::GetAll
    events:
      - http:
          path: api/teams/{teamId}/habits
          method: get
          request:
            parameters:
              paths:
                teamId: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-west-2:640097525811:userpool/us-west-2_d6v3kKOTn
  get-habit:
    handler: HabitsEngine::Habits.API.HabitHandler::Get
    events:
      - http:
          path: api/teams/{teamId}/habits/{habitId}
          method: get
          request:
            parameters:
              paths:
                teamId: true
                habitId: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-west-2:640097525811:userpool/us-west-2_d6v3kKOTn
  post-habit:
    handler: HabitsEngine::Habits.API.HabitHandler::Add
    events:
      - http:
          path: api/teams/{teamId}/habits
          method: post
          request:
            parameters:
              paths:
                teamId: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-west-2:640097525811:userpool/us-west-2_d6v3kKOTn
  put-habit:
    handler: HabitsEngine::Habits.API.HabitHandler::Update
    events:
      - http:
          path: api/teams/{teamId}/habits
          method: put
          request:
            parameters:
              paths:
                teamId: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-west-2:640097525811:userpool/us-west-2_d6v3kKOTn
  delete-habit:
    handler: HabitsEngine::Habits.API.HabitHandler::Delete
    events:
      - http:
          path: api/teams/{teamId}/habits/{habitId}
          method: delete
          request:
            parameters:
              paths:
                teamId: true
                habitId: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-west-2:640097525811:userpool/us-west-2_d6v3kKOTn
  get-tasks:
    handler: HabitsEngine::Habits.API.TaskHandler::GetAll
    events:
      - http:
          path: api/habits/{habitId}/tasks
          method: get
          request:
            parameters:
              paths:
                habitId: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-west-2:640097525811:userpool/us-west-2_d6v3kKOTn
  get-task:
    handler: HabitsEngine::Habits.API.TaskHandler::Get
    events:
      - http:
          path: api/habits/{habitId}/tasks/{taskId}
          method: get
          request:
            parameters:
              paths:
                habitId: true
                taskId: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-west-2:640097525811:userpool/us-west-2_d6v3kKOTn
  post-task:
    handler: HabitsEngine::Habits.API.TaskHandler::Add
    events:
      - http:
          path: api/habits/{habitId}/tasks
          method: post
          request:
            parameters:
              paths:
                habitId: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-west-2:640097525811:userpool/us-west-2_d6v3kKOTn
  put-task:
    handler: HabitsEngine::Habits.API.TaskHandler::Update
    events:
      - http:
          path: api/habits/{habitId}/tasks
          method: put
          request:
            parameters:
              paths:
                habitId: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-west-2:640097525811:userpool/us-west-2_d6v3kKOTn
  delete-task:
    handler: HabitsEngine::Habits.API.TaskHandler::Delete
    events:
      - http:
          path: api/habits/{habitId}/tasks/{taskId}
          method: delete
          request:
            parameters:
              paths:
                habitId: true
                taskId: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-west-2:640097525811:userpool/us-west-2_d6v3kKOTn

resources:
    - ${file(serverless/cognito-user-pool.yml)}
    - ${file(serverless/cognito-identity-pool.yml)}