service: habits-api
#app: your-app-name
#tenant: your-tenant-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: dotnetcore2.1
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"

package:
  artifact: bin/release/netcoreapp2.1/HabitsEngine.zip

functions:
  get-teams:
    handler: HabitsEngine::Habits.API.TeamHandler::GetAll
    events:
      - http:
          path: api/teams
          method: get
          # authorizer:
          #   name: authorizer
          #   arn: arn:aws:cognito-idp:us-west-2:640097525811:userpool/us-west-2_DyfHujw5j
  get-team:
    handler: HabitsEngine::Habits.API.TeamHandler::Get
    events:
      - http:
          path: api/teams/{teamId}
          method: get
          request:
            parameters:
              paths:
                teamId: true
  post-team:
    handler: HabitsEngine::Habits.API.TeamHandler::Add
    events:
      - http:
          path: api/teams
          method: post
  put-team:
    handler: HabitsEngine::Habits.API.TeamHandler::Update
    events:
      - http:
          path: api/teams
          method: put
  delete-team:
    handler: HabitsEngine::Habits.API.TeamHandler::Delete
    events:
      - http:
          path: api/teams/{teamId}
          method: delete
          request:
            parameters:
              paths:
                teamId: true
  get-challenges:
    handler: HabitsEngine::Habits.API.ChallengeHandler::GetAll
    events:
      - http:
          path: api/teams/{teamId}/challenges
          method: get
          request:
            parameters:
              paths:
                teamId: true
  get-challenge:
    handler: HabitsEngine::Habits.API.ChallengeHandler::Get
    events:
      - http:
          path: api/teams/{teamId}/challenges/{challengeId}
          method: get
          request:
            parameters:
              paths:
                teamId: true
                challengeId: true
  post-challenge:
    handler: HabitsEngine::Habits.API.ChallengeHandler::Add
    events:
      - http:
          path: api/teams/{teamId}/challenges
          method: post
          request:
            parameters:
              paths:
                teamId: true
  put-challenge:
    handler: HabitsEngine::Habits.API.ChallengeHandler::Update
    events:
      - http:
          path: api/teams/{teamId}/challenges
          method: put
          request:
            parameters:
              paths:
                teamId: true
  delete-challenge:
    handler: HabitsEngine::Habits.API.ChallengeHandler::Delete
    events:
      - http:
          path: api/teams/{teamId}/challenges/{challengeId}
          method: delete
          request:
            parameters:
              paths:
                teamId: true
                challengeId: true
  get-tasks:
    handler: HabitsEngine::Habits.API.TaskHandler::GetAll
    events:
      - http:
          path: api/challenges/{challengeId}/tasks
          method: get
          request:
            parameters:
              paths:
                challengeId: true
  get-task:
    handler: HabitsEngine::Habits.API.TaskHandler::Get
    events:
      - http:
          path: api/challenges/{challengeId}/tasks/{taskId}
          method: get
          request:
            parameters:
              paths:
                challengeId: true
                taskId: true
  post-task:
    handler: HabitsEngine::Habits.API.TaskHandler::Add
    events:
      - http:
          path: api/challenges/{challengeId}/tasks
          method: post
          request:
            parameters:
              paths:
                challengeId: true
  put-task:
    handler: HabitsEngine::Habits.API.TaskHandler::Update
    events:
      - http:
          path: api/challenges/{challengeId}/tasks
          method: put
          request:
            parameters:
              paths:
                challengeId: true
  delete-task:
    handler: HabitsEngine::Habits.API.TaskHandler::Delete
    events:
      - http:
          path: api/challenges/{challengeId}/tasks/{taskId}
          method: delete
          request:
            parameters:
              paths:
                challengeId: true
                taskId: true
# resources:
#   Resources:
#     CognitoUserPool:
#       Type: "AWS::Cognito::UserPool"
#       Properties:
#         MfaConfiguration: OFF
#         UserPoolName: habits-user-pool
#         UsernameAttributes:
#           - email
#         Policies:
#           PasswordPolicy:
#             MinimumLength: 6
#     CognitoUserPoolClient:
#       Type: "AWS::Cognito::UserPoolClient"
#       Properties:
#         ClientName: habits-user-pool-client
#         GenerateSecret: False
#         UserPoolId:
#           Ref: CognitoUserPool
#     ApiGatewayAuthorizer:
#       DependsOn:
#         - ApiGatewayRestApi
#       Type: AWS::ApiGateway::Authorizer
#       Properties:
#         Name: cognito-authorizer
#         IdentitySource: method.request.header.Authorization
#         RestApiId:
#           Ref: ApiGatewayRestApi
#         Type: COGNITO_USER_POOLS
#         ProviderARNs:
#           - Fn::GetAtt: [CognitoUserPool, Arn]